# Generated by Django 6.0.2 on 2026-02-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_booking_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
    ]
